title: Luke Cohen # your name (or website title) here
logo: "/images/Cohen_Luke_2017_18.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a recent graduate from the University of Michigan, Ann Arbor where I graduated with a BSE in Computer Engineering. My classload consisted of 
  a plethora of both Electrical Engineering and Computer Science classes where I was able to learn about a bredth of topics ranging from embedded system 
  development all the way to an introduction to image processing. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/luke-cohen-071018154/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://gitlab.eecs.umich.edu/lukecohe/">View My GitLab Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
